apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: k8s-sched
build:
  local:
    push: false
  artifacts:
    - image: mock-sandbox
      context: mock-sandbox
    - image: scheduler
      docker:
        dockerfile: Dockerfile.scheduler
    - image: activator
      docker:
        dockerfile: Dockerfile.activator
portForward:
- resourceType: service
  resourceName: activator
  namespace: sandbox
  port: 80
  localPort: 8080
- resourceType: service
  resourceName: envoy
  namespace: sandbox
  port: 80
  localPort: 8081
- resourceType: service
  resourceName: envoy
  namespace: sandbox
  port: 9901
  localPort: 9901
manifests:
  kustomize:
    paths:
      - k8s/overlays/dev