apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: k8s-sched
build:
  local:
    push: false
  artifacts:
    - image: mock-sandbox
      ko:
        dir: mock-sandbox
        main: ./cmd/sandbox
        dependencies:
          paths:
            - mock-sandbox/**/*.go
    - image: scheduler
      ko:
        main: ./scheduler/cmd/server
        dependencies:
          paths:
            - scheduler/**/*.go
            - gen/**/*.go
    - image: activator
      ko:
        main: ./activator/cmd/activator
        dependencies:
          paths:
            - activator/**/*.go
            - gen/**/*.go
portForward:
- resourceType: service
  resourceName: envoy
  namespace: sandbox
  port: 80
  localPort: 8080
- resourceType: service
  resourceName: envoy
  namespace: sandbox
  port: 9901
  localPort: 9901
manifests:
  kustomize:
    paths:
      - k8s/overlays/dev