apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: sandbox
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: sandbox
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    name: redis
  type: ClusterIP 