apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler
  namespace: sandbox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scheduler-role
  namespace: sandbox
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scheduler-role-binding
  namespace: sandbox
subjects:
- kind: ServiceAccount
  name: scheduler
  namespace: sandbox
roleRef:
  kind: Role
  name: scheduler-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: sandbox
  labels:
    app: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      serviceAccountName: scheduler
      containers:
      - name: scheduler
        image: scheduler:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
          name: grpc
        env:
        - name: KUBERNETES_NAMESPACE
          value: "sandbox"
        - name: REDIS_URI
          value: "redis://redis:6379/0"
        - name: PORT
          value: "50051"
        - name: NAMESPACE
          value: "sandbox"
        - name: DEV_LOGGING
          value: "true"
        - name: SANDBOX_IMAGE
          value: "mock-sandbox:latest"
        - name: IDEMPOTENCE
          value: "redis"        
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler
  namespace: sandbox
spec:
  selector:
    app: scheduler
  ports:
  - port: 50051
    name: grpc
  type: ClusterIP 