apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: sandbox
spec:
  selector:
    app: envoy
  ports:
  - port: 80
    targetPort: 8080
    name: http
  - port: 9901
    targetPort: 9901
    name: admin
  type: ClusterIP 