apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
      - name: envoy
        image: envoyproxy/envoy:distroless-v1.34-latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9901
          name: admin
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: envoy-config
        configMap:
          name: envoy-config
          items:
            - key: envoy-config.yaml
              path: envoy.yaml 