apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sandbox-namespace.yaml
  - redis-deployment.yaml
  - scheduler-deployment.yaml
  - activator-deployment.yaml
  - envoy-deployment.yaml
  - envoy-service.yaml

# Use ConfigMap generators for Envoy configuration
configMapGenerator:
  - name: envoy-config
    namespace: sandbox
    files:
      - envoy/envoy-config.yaml 